---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hp6xh47j1ds2/public_html/crm/simple_auth
    - /bin/cp -Rf . $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml
